### PR TITLE
Add publication_name config setting

### PR DESCRIPTION
**Pull request by jgeurts**

### CODE REVIEW

**Comment by beevital** [comment]
We need to support this field in go-fivetran SDK first.

**Comment by jgeurts** [comment]
I didn't know how to request that, so I was hoping this could kick off an internal request :)

**Comment by jgeurts** [comment]
I wasn't sure where the sdk code was located. I found it and added a PR: https://github.com/fivetran/go-fivetran/pull/34. Hopefully that helps 🤷

**Comment by beevital** [comment]
> I wasn't sure where the sdk code was located. I found it and added a PR: [fivetran/go-fivetran#34](https://github.com/fivetran/go-fivetran/pull/34). Hopefully that helps 🤷

Thank you! I will merge all the things.
Once go-fivetran new version will be released I'll update dependency here and merge it too.

**Comment by beevital** [comment]
@jgeurts I've released a new version - so you can update go-fivetran version here

**Comment by beevital** [comment]
@jgeurts all is set! Thank you!

testing fails - but it is OK, we haven't set the testing creds for external PR's for e2e tests.

**Review by beevital — APPROVED** [review]

**Pull request merged**
